C     ESTE PROGRAMA LEE UN MÈMERO "REAL"
C     E IMPRIME EL µREA DE UN C÷RCULO DE RADIO R

C     THIS PROGRAM READS A "REAL" NUMBER
C     AND PRINT THE AREA OF A CIRCLE OF RADIUS R
      PROGRAM CIRCLE
C     DECLARACIONES
C     DECLARATIONS
      REAL R, AREA
      PARAMETER (PI = 3.141592)
C     INSTRUCCIONES
C     INSTRUCTIONS
      WRITE (*,*) 'Input radius: '
      READ (*,*) R
      AREA = PI*R*R
      WRITE (*,*) 'Area= ', AREA

C     USAR EL READ PARA PODER VER EL RESULTADO
C     USE THIS READ TO SEE THE RESULT
      READ (*,*)
      STOP
      END
